export type AdminProduct = {
  id: string | number;
  name: string;
  slug: string;
  description: string | null;
  shortDescription?: string | null;
  short_description?: string | null;
  price: number;
  buyingPrice?: number;
  buying_price?: number;
  salePrice?: number | null;
  sale_price?: number | null;
  compareAtPrice?: number | null;
  compare_at_price?: number | null;
  sku?: string | null;
  status?: "draft" | "published" | "archived";
  material?: string | null;
  seoTitle?: string | null;
  seo_title?: string | null;
  seoDescription?: string | null;
  seo_description?: string | null;
  featuredImageUrl?: string | null;
  featured_image_url?: string | null;
  categoryId?: string | number | null;
  category_id?: string | number | null;
  category: string;
  featured: boolean;
  bestSeller?: boolean;
  best_seller?: boolean;
  newArrival?: boolean;
  new_arrival?: boolean;
  in_stock?: boolean;
  stock_count?: number;
  stockCount?: number;
  quantity?: number;
  stockStatus?: "IN_STOCK" | "LOW_STOCK" | "OUT_OF_STOCK";
  stock_status?: "IN_STOCK" | "LOW_STOCK" | "OUT_OF_STOCK";
  imageUrls?: string[];
  images?: Array<{ id: string | number; url: string; sortOrder: number }>;
  colors: Array<{ name: string; hex: string }>;
  sizes: string[];
  specifications: string[];
  product_images?: Array<{
    id: string | number;
    url: string;
    alt_text?: string;
    is_primary?: boolean;
  }>;
};

export type ProductFormState = {
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  price: number | null;
  buyingPrice: number | null;
  compareAt: number | null;
  sku: string;
  status: "draft" | "published" | "archived";
  material: string;
  dimensions: string;
  hardware: string;
  lining: string;
  seoTitle: string;
  seoDescription: string;
  featuredImageUrl: string;
  categoryId: string;
  category: string;
  featured: boolean;
  bestSeller: boolean;
  newArrival: boolean;
  inStock: boolean;
  stockCount: number;
  imageUrlsText: string;
  existingImageIds: string[];
  removedImageIds: string[];
  colorsText: string;
  sizesText: string;
};

export type ProductEdits = Record<string, ProductFormState>;

export type ProductFieldsProps = {
  state: ProductFormState;
  onChange: <K extends keyof ProductFormState>(key: K, value: ProductFormState[K]) => void;
  categoryOptions: Array<{ value: string; label: string }>;
  errors?: Partial<Record<keyof ProductFormState, string>>;
};
